{% set name = "colorir" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colorir-{{ version }}.tar.gz
  sha256: 2938324cef3543171038f78ae682b25465d1b74fd702217b178807f59eb9e839

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - networkx

test:
  imports:
    - colorir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aleferna12/colorir
  summary: A python package for easy management of colors and palettes.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - carlodri
